server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /src/;
    }

    location /src/ {
        try_files $uri $uri/ /src/index.html;
    }

    location /public/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
